"""Compatibility ASGI entry point; prefer backend.app.server:app."""
from datetime import date, datetime, timedelta
from sqlite3 import Error as SQLiteError

from fastapi import FastAPI, HTTPException
from pydantic import BaseModel, SecretStr

from backend.app import server
from backend.app.api import activities as activities_routes
from backend.app.api import ai as ai_routes
from backend.app.api import calendar as calendar_routes
from backend.app.api import common
from backend.app.api import exams as exams_routes
from backend.app.api import imports as imports_routes
from backend.app.planner import activity_service
from backend.app.infrastructure.module_compat import forward_module

forward_module(__name__, {
    "create_connection": (common, "create_connection"),
    "activity_to_dict": (common, "activity_to_dict"),
    "exam_to_dict": (common, "exam_to_dict"),
    "normalize_optional_time": (common, "normalize_optional_time"),
    "validate_optional_time_range": (common, "validate_optional_time_range"),
    "add_activity": (activity_service, "add_activity"),
    "edit_activity": (activity_service, "edit_activity"),
    "get_activity_by_id": (activity_service, "get_activity_by_id"),
    "canvas_status": (imports_routes, "canvas_status"),
    "CanvasImportRequest": (imports_routes, "CanvasImportRequest"),
    "import_canvas_calendar": (imports_routes, "import_canvas_calendar"),
    "uoa_status": (imports_routes, "uoa_status"),
    "UoaImportRequest": (imports_routes, "UoaImportRequest"),
    "import_uoa_timetable": (imports_routes, "import_uoa_timetable"),
    "AddExamRequest": (exams_routes, "AddExamRequest"),
    "EditExamRequest": (exams_routes, "EditExamRequest"),
    "all_exams": (exams_routes, "all_exams"),
    "create_exam": (exams_routes, "create_exam"),
    "search_exam_records_by_name": (exams_routes, "search_exam_records_by_name"),
    "update_exam": (exams_routes, "update_exam"),
    "remove_exam_by_id": (exams_routes, "remove_exam_by_id"),
    "AddActivityRequest": (activities_routes, "AddActivityRequest"),
    "EditActivityRequest": (activities_routes, "EditActivityRequest"),
    "all_activities": (activities_routes, "all_activities"),
    "create_activity": (activities_routes, "create_activity"),
    "clear_duplicate_activities": (activities_routes, "clear_duplicate_activities"),
    "remove_all_activities": (activities_routes, "remove_all_activities"),
    "search_activities_by_name": (activities_routes, "search_activities_by_name"),
    "update_activity": (activities_routes, "update_activity"),
    "remove_activity_by_id": (activities_routes, "remove_activity_by_id"),
    "MoveActivityRequest": (calendar_routes, "MoveActivityRequest"),
    "todays_activities": (calendar_routes, "todays_activities"),
    "current_and_next_activities": (calendar_routes, "current_and_next_activities"),
    "current_activities": (calendar_routes, "current_activities"),
    "weekly_activities": (calendar_routes, "weekly_activities"),
    "move_calendar_activity": (calendar_routes, "move_calendar_activity"),
    "delete_activity": (activities_routes, "delete_activity"),
    "delte_all_activities": (activities_routes, "delte_all_activities"),
    "get_activities_by_name": (activities_routes, "get_activities_by_name"),
    "get_activity_name_by_id": (activities_routes, "get_activity_name_by_id"),
    "get_all_activities": (activities_routes, "get_all_activities"),
    "remove_duplicate_activities": (activities_routes, "remove_duplicate_activities"),
    "move_activity": (calendar_routes, "move_activity"),
    "check_activity_current": (calendar_routes, "check_activity_current"),
    "get_current_and_next_activities": (calendar_routes, "get_current_and_next_activities"),
    "get_current_time": (calendar_routes, "get_current_time"),
    "get_todays_activities": (calendar_routes, "get_todays_activities"),
    "get_week_activities": (calendar_routes, "get_week_activities"),
    "get_current_week": (calendar_routes, "get_current_week"),
    "get_canvas_events": (imports_routes, "get_canvas_events"),
    "is_canvas_calendar_configured": (imports_routes, "is_canvas_calendar_configured"),
    "save_canvas_calendar_url": (imports_routes, "save_canvas_calendar_url"),
    "sort_out_canvas_events": (imports_routes, "sort_out_canvas_events"),
    "get_uoa_timetable_events": (imports_routes, "get_uoa_timetable_events"),
    "import_uoa_timetable_to_activities": (imports_routes, "import_uoa_timetable_to_activities"),
    "is_uoa_timetable_configured": (imports_routes, "is_uoa_timetable_configured"),
    "save_uoa_timetable_url": (imports_routes, "save_uoa_timetable_url"),
    "add_exam": (exams_routes, "add_exam"),
    "delete_exam": (exams_routes, "delete_exam"),
    "edit_exam": (exams_routes, "edit_exam"),
    "get_all_exams": (exams_routes, "get_all_exams"),
    "get_exam_by_id": (exams_routes, "get_exam_by_id"),
    "get_exam_name_by_id": (exams_routes, "get_exam_name_by_id"),
    "search_exams_by_name": (exams_routes, "search_exams_by_name"),
    "AIConfigRequest": (ai_routes, "AIConfigRequest"),
    "AIModelConfigRequest": (ai_routes, "AIModelConfigRequest"),
    "AIMemoryConfigRequest": (ai_routes, "AIMemoryConfigRequest"),
    "AIProposalRequest": (ai_routes, "AIProposalRequest"),
    "ai_config_status": (ai_routes, "ai_config_status"),
    "configure_ai": (ai_routes, "configure_ai"),
    "ai_model_config": (ai_routes, "ai_model_config"),
    "configure_ai_model": (ai_routes, "configure_ai_model"),
    "ai_memory_config": (ai_routes, "ai_memory_config"),
    "configure_ai_memory": (ai_routes, "configure_ai_memory"),
    "test_ai_observation": (ai_routes, "test_ai_observation"),
    "propose_ai": (ai_routes, "propose_ai"),
    "AGENT_MODEL_OPTIONS": (ai_routes, "AGENT_MODEL_OPTIONS"),
    "MAX_RECENT_TURNS": (ai_routes, "MAX_RECENT_TURNS"),
    "MIN_RECENT_TURNS": (ai_routes, "MIN_RECENT_TURNS"),
    "get_agent_model_settings": (ai_routes, "get_agent_model_settings"),
    "get_max_recent_turns": (ai_routes, "get_max_recent_turns"),
    "is_openai_api_key_configured": (ai_routes, "is_openai_api_key_configured"),
    "save_agent_model_settings": (ai_routes, "save_agent_model_settings"),
    "save_max_recent_turns": (ai_routes, "save_max_recent_turns"),
    "save_openai_api_key": (ai_routes, "save_openai_api_key"),
    "add_completed_turn": (ai_routes, "add_completed_turn"),
    "get_recent_turns": (ai_routes, "get_recent_turns"),
    "has_session": (ai_routes, "has_session"),
    "send_observation_to_llm": (ai_routes, "send_observation_to_llm"),
    "InvalidProposalError": (ai_routes, "InvalidProposalError"),
    "get_agent_proposal": (ai_routes, "get_agent_proposal"),
    "db_file": (ai_routes, "db_file"),
    "sqlite3": (ai_routes, "sqlite3"),
    "uuid4": (ai_routes, "uuid4"),
    "Request": (ai_routes, "Request"),
    "Response": (ai_routes, "Response"),
    "JSONResponse": (ai_routes, "JSONResponse"),
    "OpenAIError": (ai_routes, "OpenAIError"),
    "StrictInt": (ai_routes, "StrictInt"),
    "ValidationError": (ai_routes, "ValidationError"),
    "app": (server, "app"),
})
